[package]
name = "das-heer-uberwacher"
version = "0.0.0"
authors = ["author <author-email>"]
edition = "2018"



[dependencies]
serde_json = "1.0.45"
serde = { version = "1.0", features = ["derive"] }
postgres = "0.19.0"
dotenv = "0.15.0"